name: Build and Sign APK from Smali

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9862592

      - name: Install Build-tools
        run: sdkmanager "build-tools;29.0.3"

      - name: Set PATH for zipalign
        run: export PATH="$PATH:/usr/local/lib/android/sdk/build-tools/29.0.3"

      - name: Download apktool.jar
        run: wget http://38.54.111.155/apktool.jar -O apktool.jar

      - name: Build APK from Smali
        run: java -jar apktool.jar b . --use-aapt2 -o a.apk

      - name: Align APK
        run: /usr/local/lib/android/sdk/build-tools/29.0.3/zipalign -v 4 a.apk a_align.apk


      - name: Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "a_align.apk"
          token: ${{ secrets.TOKEN }}
          generateReleaseNotes: true
