name: Build and Sign APK from Smali

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 9862592

      - name: Install Build-tools & platforms
        run: sdkmanager "build-tools;34.0.0"

      - name: Download rescource
        run: |
          wget https://github.com/632259889/testapk/releases/download/v1.0/apktool.zip -O apktool.zip
          wget https://github.com/632259889/testapk/releases/download/v1.1/android.jar -O android.jar
          wget https://github.com/632259889/testapk/releases/download/v1.3/bundletool-all-1.15.6.jar -O bundletool.jar
          wget https://github.com/632259889/testapk/releases/download/v1.4/am.keystore -O release.keystore
        working-directory: ..

      - name: Unzip apktool
        run: unzip apktool.zip
        working-directory: /Users/runner/work/testapk

      #smali 代码转成apk
      - name: Build APK from Smali
        run: java -jar ./apktool/apktool.jar b ./testapk/ --use-aapt2 -o a.apk
        working-directory: /Users/runner/work/testapk

      # - name: Align APK
      #   run: /Users/runner/Library/Android/sdk/build-tools/34.0.0/zipalign -v 4 a.apk a_align.apk
      #   working-directory: /Users/runner/work/testapk

      # - name: Sign APK
      #   run: /Users/runner/Library/Android/sdk/build-tools/34.0.0/apksigner sign --ks release.keystore --ks-pass pass:'${{ secrets.KEY_STORE_PASSWORD }}' --out a_align_sign.apk a_align.apk
      #   working-directory: /Users/runner/work/testapk

      #apk转成aab如下
      #1.apktool解压apk
      - name: Apktool Unzip AAB
        run: java -jar ./apktool/apktool.jar d a.apk -s -o old_apk_dir
        working-directory: /Users/runner/work/testapk

      #2.aapt2 编译生成*.flat文件集合
      - name: AAPT2 Compile Res
        run: /Users/runner/Library/Android/sdk/build-tools/34.0.0/aapt2 compile --dir old_apk_dir/res -o compiled_res.zip
        working-directory: /Users/runner/work/testapk

      #3.aapt2 关联资源
      - name: AAPT2 Link Res
        run: |
          /Users/runner/Library/Android/sdk/build-tools/34.0.0/aapt2 link --proto-format -o base.apk -I /Users/runner/work/testapk/android.jar --min-sdk-version 26 --target-sdk-version 33 --version-code 100 --version-name 1.0.0 --manifest old_apk_dir/AndroidManifest.xml -R compiled_res.zip --auto-add-overlay
          unzip base.apk -d new_apk_dir
        working-directory: /Users/runner/work/testapk

      #4.创建对应的结构目录
      - name: Create App Bundle Destory
        run: |
          mkdir manifest
          mkdir root
          mkdir root/META-INF
          mkdir dex
          cp AndroidManifest.xml ./manifest
          rm -rf AndroidManifest.xml
          cp -r /Users/runner/work/testapk/old_apk_dir/lib .
          cp -r /Users/runner/work/testapk/old_apk_dir/assets .
          cp -r /Users/runner/work/testapk/old_apk_dir/unknown/* ./root/
          cp -r /Users/runner/work/testapk/old_apk_dir/kotlin ./root
          cp -r /Users/runner/work/testapk/old_apk_dir/*.dex ./dex
          zip -r new_apk.zip .
        working-directory: /Users/runner/work/testapk/new_apk_dir

        #5.利用budletool编译aab
      - name: Bundletool Zip To AAB
        run: java -jar /Users/runner/work/testapk/bundletool.jar build-bundle --modules=new_apk.zip --output=release.aab
        working-directory: /Users/runner/work/testapk/new_apk_dir

        #6.利用jarsigner对aab进行签名
      - name: Sign AAB
        run: jarsigner -digestalg SHA-256 -sigalg SHA256withRSA -keystore ./release.keystore -storepass '${{ secrets.KEY_STORE_PASSWORD }}' -keypass '${{ secrets.KEY_PASSWORD }}' ./new_apk_dir/release.aab '${{ secrets.ALIAS }}'
        working-directory: /Users/runner/work/testapk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ secrets.VERSION }}
          release_name: Release ${{ secrets.VERSION }}
          commit: main

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}{?name,label}
          asset_path: /Users/runner/work/testapk/new_apk_dir/release.aab
          asset_name: release.aab
          asset_content_type: application/octet-stream
          asset_label: important
          working-directory: /Users/runner/work/testapk
